version: '3.8'

services:
  api-gateway:
    build: ./ApiGateway
    ports:
      - "8080:8080"
    depends_on:
      - auth-service
      - product-service
      - order-service
      - payment-service
      - notification-service
      - discovery-service

  auth-service:
    build: ./AuthService
    ports:
      - "8081:8081"
    depends_on:
      - auth-db

  product-service:
    build: ./ProductService
    ports:
      - "8082:8082"
    depends_on:
      - product-db
      - redis

  order-service:
    build: ./OrderService
    ports:
      - "8083:8083"
    depends_on:
      - order-db
      - rabbitmq

  notification-service:
    build: ./NotificationService
    ports:
      - "8085:8085"
    depends_on:
      - rabbitmq

  payment-service:
    build: ./PaymentService
    ports:
      - "8086:8086"
    depends_on:
      - payment-db

  discovery-service:
    build: ./DiscoveryService
    ports:
      - "8761:8761"

  #Object Storage
  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password
    command: server /data --console-address ":9001"
    volumes:
      - ./minio/data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"]
      interval: 30s
      timeout: 20s
      retries: 3

  # Databases
  auth-db:
    image: postgres:latest
    environment:
      POSTGRES_DB: tr_auth_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password

  product-db:
    image: postgres:latest
    environment:
      POSTGRES_DB: tr_product_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password

  order-db:
    image: postgres:latest
    environment:
      POSTGRES_DB: tr_order_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password



  payment-db:
    image: postgres:latest
    environment:
      POSTGRES_DB: tr_payment_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
